### ISSUE TITLE
Windows worker out of space & clean-workspaces erroring

### ISSUE THREAD

**Issue by alanshaw** [ipfs-inactive/dev-team-enablement#135]
## Which Project is this about?

Jenkins CI

<img width="679" alt="screen shot 2018-09-10 at 12 16 13" src="https://user-images.githubusercontent.com/152863/45294522-7ce16900-b4f3-11e8-929d-eea12ef52bf4.png">

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/view/System/job/clean-workspaces/

## Which platform did the issue happen on?

Windows

**Comment by alanshaw** [comment]
Still happening today :(

**Comment by VictorBjelkholm** [comment]
Fixed the script to not fail entirely if it fails to delete one directory (seems gx is keeping itself running at some points). Works better now.

There is a separate issue on Windows workers only though, as it seems the `cleanWS` function doesn't really delete the files as it does on macOS and Linux workers. Will be looking into that closer.

**Comment by alanshaw** [comment]
FYI, a while ago I [made changes to js-ipfs to clean up after itself](https://github.com/ipfs/js-ipfs/pull/1541/commits/541fa825506d7267ecbba289f2caed97bec0f27b) to help alleviate this problem, but for failures and timeouts it might not cleanup.

Really, I think we don't want any state hanging around on the machines from prior runs. It would be nice if the machine could just be reset to a given state for each run.

**Comment by lidel** [comment]
I also got `Error: ENOSPC: no space left on device, write` on Windows:

- https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-companion/detail/PR-584/2/pipeline

Not sure why, [Companion's Jenkinsfile](https://github.com/ipfs-shipyard/ipfs-companion/blob/e4388fd46877913560626f207af0910793c146f4/ci/Jenkinsfile#L77-L78) should do cleanup at the end, even on error:

```
} finally {
  cleanWs()
}
```

Did it run out of space due to an other project/issue or is `cleanWs()` not as effective as I assumed?

**Comment by daviddias** [comment]
Still an issue? Consolidate with the CI exploration on ipfs/infra?

**Comment by lidel** [comment]
I am quite sure @victorb  squashed this specific one
(some temp files were not cleared properly on Windows).
